name: pre-commit

on:
  push:
    branches:
      - '**'  # This will match all branches
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: nbstripout --all-files
