name: pre-commit

on:
  push:
    branches:
      - '**'  # This will match all branches
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Set up python
      uses: actions/setup-python@v3

      - name: Install pre-commit
      run: 
      pip install pre-commit
      pre-commit install
      
      - name: Run pre-commit checks
      uses: pre-commit/action@v3.0.1
        with:
          extra_args: nbstripout --all-files
